variable "server_public_ip" {
  type        = string
  description = "Wireguard server public static IP"
}

variable "server_private_key" { # TODO: we probably need to have this set as sensitive
  type        = string
  description = "Wireguard server private key, which can be generated using wg cli tool: `wg genkey > privatekey-server`"
}

variable "server_public_key" {
  type        = string
  description = "Wireguard server public key, which can be generated using wg cli tool and server private key: `wg pubkey < privatekey-server > publickey-server`"
}

variable "network_cidr" {
  type        = string
  default     = "10.11.11.0/24" # client/peer valid IPs for this default value are in range 10.11.11.1 - 10.11.11.255
  description = "Wireguard network CIDR which should not overlap with local/server networks"
}

variable "clients" {
  type = list(object({
    name            = string                                   # should be unique in list
    ip              = string                                   # client uniq IP form var.network_cidr range in cidr format, TODO: we maybe can automate this IP creation inside module
    route_ip_ranges = string                                   # comma separated IP ranges that the client should route via the VPN in format "1.2.3.4/32,1.1.1.1/16", set "0.0.0.0/0" to route all traffic through VPN
    public_key      = string                                   # public key of client/peer, both private and public keys can be generated by using wg cli and client private key: `wg pubkey < privatekey-client1 > publickey-client1`, # TODO: we probably need to have this set as sensitive
    private_key     = optional(string, "{client-private-key}") # client private key, pass in case you want to get fully prepared to use client_configs output, can be generated using wg cli: `wg genkey > privatekey-client1`
  }))
  default     = []
  description = "Wireguard clients/peers list with configs"
}

variable "server_port" {
  type        = number
  default     = 51820
  description = "Wireguard server port number"
}

variable "dns" {
  type        = string
  default     = "8.8.8.8"
  description = "Custom DNS server"
}

variable "keep_alive" {
  type        = number
  default     = 25
  description = "CLients peer connection persistance keep alive config"
}

variable "ingress" {
  type        = list(any)
  default     = ["0.0.0.0/0"] # default to all
  description = "The IPs/CIDRs from where the instance wireguard and ssh port are open to connect"
}
